export const QUALITY_MAX_DECODED_BYTES_PER_FILE = 20 * 1024;
export const QUALITY_MAX_AST_NODES = 12_000;
export const QUALITY_MAX_NESTING_DEPTH = 128;
export const QUALITY_MAX_IMPORTS = 256;
export const QUALITY_MAX_SYMBOLS = 2_048;
export const QUALITY_MAX_TOKENS = 24_000;
export const QUALITY_PARSER_WALL_TIME_MS = 500;
