import type { PrivateContextResult } from "@gitmog/private-context";

const unavailableDimensions = {
  correctnessDiscipline: {
    available: false,
    previewScore: null,
    previewWeight: 4,
    measuredPoints: null,
    observations: 0,
  },
  testQuality: {
    available: false,
    previewScore: null,
    previewWeight: 2,
    measuredPoints: null,
    observations: 0,
  },
  maintainability: {
    available: false,
    previewScore: null,
    previewWeight: 7,
    measuredPoints: null,
    observations: 0,
  },
  contractQuality: {
    available: false,
    previewScore: null,
    previewWeight: 4,
    measuredPoints: null,
    observations: 0,
  },
  architecture: {
    available: false,
    previewScore: null,
    previewWeight: 5,
    measuredPoints: null,
    observations: 0,
  },
  securityHygiene: {
    available: false,
    previewScore: null,
    previewWeight: 4,
    measuredPoints: null,
    observations: 0,
  },
  duplicationAndDeadPatterns: {
    available: false,
    previewScore: null,
    previewWeight: 3,
    measuredPoints: null,
    observations: 0,
  },
} as const;

export const PRIVATE_CONTEXT_FIXTURE: PrivateContextResult = {
  version: "1.1.0-selected-sample-presentation",
  mode: "selected-private-repositories",
  status: "partial",
  subject: "StrongMaintainer",
  relationship: "maintained-and-attributed",
  scoreInfluence: 0,
  publicWinnerInfluence: 0,
  persisted: false,
  repositorySelection: {
    installedPrivateRepositories: 4,
    consideredRepositories: 4,
    analyzedRepositories: 4,
    maintainedRepositories: 3,
    attributableRepositories: 2,
  },
  repositorySignals: {
    activeRepositories: 3,
    substantialRepositories: 2,
    repositoriesWithTests: 3,
    repositoriesWithCi: 3,
    repositoriesWithReleases: 1,
  },
  maintainedCodebase: {
    status: "partial",
    previewScore: 72,
    scope: "selected-sample",
    classification: "informational",
    scoreInfluence: 0,
    publicWinnerInfluence: 0,
    persisted: false,
    coverage: 61,
    dimensions: unavailableDimensions,
    repositories: 3,
    files: 10,
    sourceBytes: 64_000,
    nonBlankLines: 1_200,
    languages: ["typescript"],
  },
  attributedCode: {
    status: "partial",
    previewScore: 68,
    scope: "selected-sample",
    classification: "informational",
    scoreInfluence: 0,
    publicWinnerInfluence: 0,
    persisted: false,
    coverage: 52,
    dimensions: unavailableDimensions,
    repositories: 2,
    files: 7,
    sourceBytes: 44_000,
    nonBlankLines: 800,
    languages: ["typescript", "javascript"],
  },
  limitations: [
    {
      code: "attribution",
      detail: "Some sampled files lacked user-linked commit evidence.",
      count: 3,
    },
  ],
  receipts: [
    {
      id: "P1",
      claim: "3 of 4 analyzed private repositories contain CI configuration.",
      metric: "ci-repositories",
      observed: 3,
      total: 4,
    },
    {
      id: "P2",
      claim: "2 selected private projects show sustained maintenance.",
      metric: "sustained-repositories",
      observed: 2,
      total: 4,
    },
    {
      id: "P3",
      claim: "Code-quality sample: 3 repos · 10 parsed files · 61% supported coverage.",
      metric: "quality-coverage",
      observed: 61,
      total: 100,
    },
    {
      id: "P4",
      claim: "7 of 10 sampled files have user-linked commit evidence.",
      metric: "attributed-files",
      observed: 7,
      total: 10,
    },
  ],
  requestTelemetry: {
    version: "1.0.0-bounded-private-rest",
    requests: 24,
    requestCap: 64,
    requestCapPerRepository: 12,
    identityRequests: 1,
    installationRequests: 1,
    repositoryListRequests: 1,
    repositoryMetadataRequests: 6,
    sourceRequests: 10,
    attributionRequests: 5,
  },
};
